version: 2

updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    labels:
      - 🧩 dependencies
      - 🤖 bot

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
    labels:
      - 🧩 dependencies
      - 🤖 bot

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels:
      - 🧩 dependencies
      - 🤖 bot